---
title: "Uploading Data"
output: html_document
---

***The maximum file upload size is: 50Mb***

The following file formats are supported for the uploading your bulk expression profiles: **csv**, **tsv**, **xlsx**.

All uploaded data should have samples in columns and genes in rows. The first column of your data should contain your gene symbols and be in string/character format. Moreover, all genes and sample names should be unique:

<br/>
<image src= "example_input.png" width = "100%"/>

<br/>

Data expression values should be normalised such that the expression levels are comparable between samples. The method for achieving this is not strictly enforced, but some popular methods are:



**TPM** - transcripts per kilobase million

**CPM** - counts per million

**Median of Ratios (DESeq2)**

**TMM (EdgeR)** - trimmed mean of M values

<br/>

All expression values are scaled during the scoring process and therefore, must ***NOT*** be on a logarithmic scale as this will result in scores that may be un-interpretable.
